### ISSUE TITLE
config.json

### ISSUE THREAD

**Issue by Vakrehus** [seb-daehne/dvb-mqtt#2]
Versuche seit Stunden den Container zum laufen zu bekommen. Ich nutze Portainer und komme mit ENV sehr gut zurecht, jedoch nicht mit einer 'config.json'. Keinen Ahnung, wo ich diese einbinden kann.
Habe eine Verzeichnis in meinem Dockerverzeichnis erstellt und als Volume gemountet. Darin befindet sich die config.json.

Bin mir auch mit dem mqttbroker unsicher - dieser hat einen Nutzernamen und ein Passwort. Müsste das dann so aussehen?
`  "mqttBroker" : "tcp://USER:PASS@192.168.1.100:1883",`

Ziel ist es, die Abfahrtzeiten der Haltestelle in Home Assistant einzubinden.

**Comment by Vakrehus** [comment]
Unter Portainer funktioniert das freigeben eines files, nicht wie mit einer Volume `type=bind` hat bei der 'config.json' geholfen.

Jedoch komm ich dann nicht weiter. Folgende Meldungen erscheinen, obwohl die richtige IP in der config steht.
```
City:
+ start
panic: network Error : dial tcp: missing address

goroutine 1 [running]:
main.publishDepartures(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x8433900, ...)
	/build/request_dvb.go:113 +0x4dc
main.main()
	/build/request_dvb.go:139 +0xbc
```

**Comment by seb-daehne** [comment]
Hi, das liegt leider daran das authentication noch nicht supported ist - ich bau das mal ein.
